# Generated by Django 6.0.6 on 2026-06-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('cover_image', models.CharField(blank=True, default='', max_length=500)),
                ('date', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('publie', 'Publié'), ('brouillon', 'Brouillon')], default='publie', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='faqitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='status',
            field=models.CharField(choices=[('publie', 'Publié'), ('brouillon', 'Brouillon')], default='publie', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='localisation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='realisation',
            name='stats',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
