# Generated by Django 6.0.6 on 2026-06-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmssetting',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
