# Generated by Django 6.0.6 on 2026-06-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cmssetting_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='candidatures/cv/'),
        ),
    ]
